source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
#AF'~> 3.4'
#MP, '~> 2.9'
target 'WingBoardKeyboard' do
    pod 'Alamofire', '~> 4.4'
#    pod 'AppsFlyerFramework'
#    pod 'Mixpanel/AppExtension'
    pod 'AppsFlyerFramework'

end

target 'WingBoard' do
    pod 'Alamofire', '~> 4.4'
    pod 'Mixpanel'
    

end

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['SWIFT_VERSION'] = '2.3'
    end
end
